---
services:
  web:
    build: 
      context: .
      dockerfile: app/Dockerfile
    command: uwsgi --ini /home/esterilizaya/config/uwsgi/uwsgi.ini
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - db_password
      - admin_password
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD_FILE=${DB_PASSWORD_FILE}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DJANGO_SETTINGS_MODULE=esterilizaya.settings.prod
    volumes:
      - "media-volume:/home/esterilizaya/code/media"
      - ./app:/home/esterilizaya/code

  db:
    image: mariadb:11
    restart: always
    command: "--default-authentication-plugin=ed25519"
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=${DB_ROOT_PASSWORD_FILE}
      - MARIADB_PASSWORD_FILE=${DB_PASSWORD_FILE}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
    secrets:
      - db_root_password
      - db_password
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "maria-db:/var/lib/mysql"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./app/:/home/esterilizaya/code
      - media-volume:/home/esterilizaya/code/media
    ports:
    - "80:80"
    - "443:443"
secrets:
  db_root_password:
    file: credenciales/database/root_password.txt
  db_password:
    file: credenciales/database/user_password.txt
  admin_password:
    file: credenciales/database/admin_password.txt

volumes:
  maria-db:
    driver: local
  media-volume:
    driver: local
