---
services: 
  web: 
    build: app 
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - '8000:8000'
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - db_password
      - admin_password
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD_FILE=${DB_PASSWORD_FILE}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}

  db:
    image: mariadb:11
    restart: always
    command: '--default-authentication-plugin=ed25519'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=${DB_ROOT_PASSWORD_FILE}
      - MARIADB_PASSWORD_FILE=${DB_PASSWORD_FILE}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
    secrets:
      - db_root_password
      - db_password
    ports:
      - '${DB_PORT}:3306'

secrets:
  db_root_password:
    file: database/credenciales/root_password.txt
  db_password:
    file: database/credenciales/user_password.txt
  admin_password:
    file: database/credenciales/admin_password.txt