---
services:
  web:
    command: uwsgi --ini /home/esterilizaya/config/uwsgi/uwsgi.ini
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=esterilizaya.settings.prod
      - REQUESTS_CA_BUNDLE=/home/esterilizaya/code/ssl/happypaws.crt
    volumes:
      - ./pdfs:/tmp/pdfs
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./app/:/home/esterilizaya/code
      - media-volume:/home/esterilizaya/code/media
    ports:
      - "80:80"
      - "443:443"
