services:
 web:
  restart: no
  build:
   target: prod
  volumes:
   - ./app:/home/esterilizaya/code
  command: sh -c "python manage.py makemigrations campana inscripcion registro && python manage.py migrate"
